### ISSUE TITLE
Login with Devise

### ISSUE THREAD

**Issue by mmalek-sa** [rbCAS/casino-activerecord_authenticator#11]
I just cloned CASinoAPP and changed Gemfile to casino3:

```
source 'https://rubygems.org'

gem 'rails', '4.1.0'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'therubyracer'
end

gem 'casino', '3.0.0.pre.1'
gem 'casino-activerecord_authenticator', :github => 'rbCAS/casino-activerecord_authenticator', :branch => 'casino3'

gem 'whenever', :require => false

group :sqlite do
  gem 'sqlite3'
end

group :mysql do
  gem 'mysql2'
end

group :postgres do
  gem 'pg'
end

group :development do
  gem 'capistrano', '~> 2.15'
end 
```

then edited my cas.yml to connect to my postgre database with devise:

```
production:
  frontend:
    sso_name: 'Acceptto SSO'
    footer_text: 'All rights reserved by Acceptto'
  authenticators:

########################################
# SQL (ActiveRecord authenticator)
########################################
    my_company_sql_database:
      authenticator: "ActiveRecord"
      options:
        connection:
          host: localhost
          adapter: postgresql
          database: m2m_development
          encoding: unicode
          pool: 5
          username: acceptto
          password: vesper
        table: "users"
        username_column: "email"
        password_column: "encrypted_password"
        extra_attributes:
          email: "email"
          fullname: "email"
```

After starting the server and trying to login I get this log message in Terminal:

```
Started POST "/login" for 127.0.0.1 at 2014-05-11 12:49:06 +0430
Processing by CASino::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"052B5FNnci1HKSJis7BKn1c8jZU70Mq+bh+dsOZAYqU=", "lt"=>"LT-13997963103773-LzfYWg0YEThYA8kPyd6Kw9X0N09bPHMWx2SM5jxB", "username"=>"mm.mani@icloud.com", "password"=>"[FILTERED]", "rememberMe"=>"1", "button"=>""}
  CASino::LoginTicket Load (0.8ms)  SELECT  "casino_login_tickets".* FROM "casino_login_tickets"  WHERE "casino_login_tickets"."ticket" = 'LT-13997963103773-LzfYWg0YEThYA8kPyd6Kw9X0N09bPHMWx2SM5jxB' LIMIT 1
Login ticket 'LT-13997963103773-LzfYWg0YEThYA8kPyd6Kw9X0N09bPHMWx2SM5jxB' successfully validated
  SQL (1.3ms)  DELETE FROM "casino_login_tickets" WHERE "casino_login_tickets"."id" = 14
   (0.3ms)  BEGIN
  CASino::LoginTicket Exists (0.6ms)  SELECT  1 AS one FROM "casino_login_tickets"  WHERE "casino_login_tickets"."ticket" = 'LT-13997963466853-t4HTBMOgx8sHv7xzT9imSsactLrY7lusc4ZKCAyK' LIMIT 1
  SQL (0.7ms)  INSERT INTO "casino_login_tickets" ("created_at", "ticket", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["created_at", "2014-05-11 08:19:06.687807"], ["ticket", "LT-13997963466853-t4HTBMOgx8sHv7xzT9imSsactLrY7lusc4ZKCAyK"], ["updated_at", "2014-05-11 08:19:06.687807"]]
   (0.5ms)  COMMIT
Created login ticket 'LT-13997963466853-t4HTBMOgx8sHv7xzT9imSsactLrY7lusc4ZKCAyK'
  Rendered /Users/mani/.rvm/gems/ruby-1.9.3-p194@casinoapp/gems/casino-3.0.0.pre.1/app/views/casino/application/_messages.html.erb (0.1ms)
  Rendered /Users/mani/.rvm/gems/ruby-1.9.3-p194@casinoapp/gems/casino-3.0.0.pre.1/app/views/casino/application/_footer.html.erb (0.2ms)
  Rendered /Users/mani/.rvm/gems/ruby-1.9.3-p194@casinoapp/gems/casino-3.0.0.pre.1/app/views/casino/sessions/new.html.erb within layouts/application (6.6ms)
Completed 403 Forbidden in 23ms (Views: 13.1ms | ActiveRecord: 4.1ms)
```

it seems like login ticket validates successfully but then I get a 403 Forbidden in sessions/new.html and I get a Incorrect username or password message on the view. this is my /config/initializers/devise.rb config file on my development machine:

```
Devise.setup do |config|
  config.secret_key = '561e47b4fc7d7b3f6f33245db32c151b58a0365647c46dcf7c03807ebe968779a5b3ebb5ccf6f03d0e34161349eb8ea9d52ee6db8c3b76e1bff3058241e40e2f'
  config.mailer_sender = 'accounting@acceptto.com'
  config.mailer = 'Devise::Mailer'
  require 'devise/orm/active_record'
  config.case_insensitive_keys = [ :email ]
  config.strip_whitespace_keys = [ :email ]
  config.skip_session_storage = [:http_auth]
  config.stretches = Rails.env.test? ? 1 : 10

  # Setup a pepper to generate the encrypted password.
  # config.pepper = 'dc78514f85063bae46f6c59eca0fbcaf77058ae4184948d795dfdd7baf84f49b46be247fa3c0f2830d70b3f0c621d3cf0616d8fb52e4dcd9774075da162d4ac5'
  config.reconfirmable = true

  config.password_length = 8..128

  config.reset_password_within = 6.hours

  config.sign_out_via = :delete
end
```

as you can see pepper line is commented (default config for devise). Also my password is 'eybaba13' which is in database with this format in encrypted_password field:
$2a$10$I0wEDn3LomuW06WsYUYIyOr5Qe5fqfqdt07dXDTz2AtEEiSqeyfHK

Any Idea how to fix it?

**Comment by AjayBarot** [comment]
@pencil : I am getting the same error. Please help me to investigate the root cause.

On Server application:

**gemfile**

```
gem 'rails', '3.2.18'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'therubyracer'
end

gem 'pry'
gem 'pry-nav'

gem 'casino'
gem 'casino-activerecord_authenticator'

gem 'whenever', :require => false

group :mysql do
  gem 'mysql2', "~>0.3.11"
end

gem 'devise', '3.4.1
```

**casino 2.0.4**

**database.yml**

```
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: SSOExampleApp_developmentbackup
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
```

**devise.rb**
```
  config.secret_key = 'ebed0f769e7cb7f5eff61037ec844588ff1611bbc0c7c5d1c39c6f2aaca6971c301fc8d68d7455eb535ecb381cb27b105262e6ae4219a13b436c5457a0cc2f33'
  require 'devise/orm/active_record'
```

**Log**
```
Started POST "/login" for 127.0.0.1 at 2016-09-16 11:10:47 +0530
Processing by CASino::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"nooXt0bKB+qird4orzb1Py84JqlOFJwv1z6EqNHAvnM=", "lt"=>"LT-14740044389774-0AaFieTjcMEZnJ30CCFAh97NRf7bsB9k420HG5Uu", "service"=>"http://localhost:3000/users/service", "username"=>"test1@example.com", "password"=>"[FILTERED]", "button"=>""}
  CASino::LoginTicket Load (0.4ms)  SELECT `casino_login_tickets`.* FROM `casino_login_tickets` WHERE `casino_login_tickets`.`ticket` = 'LT-14740044389774-0AaFieTjcMEZnJ30CCFAh97NRf7bsB9k420HG5Uu' LIMIT 1
Login ticket 'LT-14740044389774-0AaFieTjcMEZnJ30CCFAh97NRf7bsB9k420HG5Uu' successfully validated
  SQL (102.0ms)  DELETE FROM `casino_login_tickets` WHERE `casino_login_tickets`.`id` = 14
   (0.1ms)  BEGIN
  CASino::LoginTicket Exists (0.3ms)  SELECT 1 AS one FROM `casino_login_tickets` WHERE `casino_login_tickets`.`ticket` = BINARY 'LT-14740044477944-bOJy15EM9ATxENwJoM5aMCP7KNmzkq8lqca5p27U' LIMIT 1
  SQL (0.2ms)  INSERT INTO `casino_login_tickets` (`created_at`, `ticket`, `updated_at`) VALUES ('2016-09-16 05:40:47', 'LT-14740044477944-bOJy15EM9ATxENwJoM5aMCP7KNmzkq8lqca5p27U', '2016-09-16 05:40:47')
   (46.5ms)  COMMIT
Created login ticket 'LT-14740044477944-bOJy15EM9ATxENwJoM5aMCP7KNmzkq8lqca5p27U'
  Rendered /home/abarot/.rvm/gems/ruby-1.9.3-p194@casinoapp/gems/casino-2.0.4/app/views/casino/application/_messages.html.erb (0.1ms)
  Rendered /home/abarot/.rvm/gems/ruby-1.9.3-p194@casinoapp/gems/casino-2.0.4/app/views/casino/application/_footer.html.erb (0.0ms)
  Rendered /home/abarot/.rvm/gems/ruby-1.9.3-p194@casinoapp/gems/casino-2.0.4/app/views/casino/sessions/new.html.erb within layouts/application (4.0ms)
Completed 403 Forbidden in 270.0ms (Views: 9.0ms | ActiveRecord: 149.4ms)
```

As you mention above I checked password encryption. But it also working fine.

**users table**

![database](https://cloud.githubusercontent.com/assets/5164950/18576473/807b899e-7bff-11e6-889e-1bd7f1f20fe6.png)

```
BCrypt::Password.new("$2a$10$vAOgBwzaSoX33Fx2YBQhJeNGfCgG0HauXJJsAA1jqCEUpTGj6Ti/K") == "12345678"
 => true
```

Thanks & Regards
Ajay Barot
